export default {
    UPDATE_CITY_REQUEST: "UPDATE_CITY_REQUEST",
    UPDATE_CITY_SUCCESS: "UPDATE_CITY_SUCCESS",
    NEXT_PAGE_REQUEST: "NEXT_PAGE_REQUEST",
    NEXT_PAGE_SUCCESS: "NEXT_PAGE_SUCCESS",
};
  